Install cypress
Julys17/cypress-training pull request #2
Opened 2023-09-24 21:37 UTC by Julys17

setup cypress configuration

2023-09-24 22:15 UTC, DanielCalleCO requested changes

2023-09-24 22:15 UTC, DanielCalleCO commented on .github/CODEOWNERS
> +@abdulflorez
Juli, descarga la última versión de main en tu local... Luego haces merge con esta rama y vuelves a hacer push en esta rama, con eso queda actualizado el PR

2023-09-24 22:50 UTC, Julys17 commented on .github/CODEOWNERS
> +@abdulflorez
Dani listo ya actualice la rama y realice el push

2023-09-27 13:39 UTC, DanielCalleCO approved these changes

2023-09-27 20:00 UTC, merged